### ISSUE TITLE
fails to handle poll data

### ISSUE THREAD

**Issue by xdrie** [karlicoss/rexport#10]
```
    raise RuntimeError(f"Unexpected type: {type(d)}")
RuntimeError: Unexpected type: <class 'praw.models.reddit.poll.PollData'>
```

**Comment by karlicoss** [comment]
Oh, thanks, never seen that!

Most likely, the fix would be simply adding [praw.models.reddit.poll.PollData](https://praw.readthedocs.io/en/latest/code_overview/other/poll.html) to [this list](https://github.com/karlicoss/rexport/blob/4d71024a29fe95606f64daf6c7682ab8ac3bc0c4/export.py#L48-L53) if you want to try it? Otherwise, I'll try creating some test poll and doing that myself when I have a bit of time.

You can also simply replace [the line that throws the exception](https://github.com/karlicoss/rexport/blob/4d71024a29fe95606f64daf6c7682ab8ac3bc0c4/export.py#L60) with `return {}`, for example, if you don't care about the polls and just want to use this in the meantime.

**Comment by xdrie** [comment]
Unfortunately I've been rather busy as of late, so it might be a while before I have time to try implementing the fix for it myself.

For now though, I'll use that workaround, thanks!

**Comment by xdrie** [comment]
I tried the fix you suggested (adding `PollData` to the list)
And I get this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/projects/rexport/src/rexport/export.py", line 140, in <module>
    main()
  File "/home/user/projects/rexport/src/rexport/export.py", line 116, in main
    j = get_json(**params)
  File "/home/user/projects/rexport/src/rexport/export.py", line 101, in get_json
    return Exporter(**params).export_json()
  File "/home/user/projects/rexport/src/rexport/export.py", line 87, in export_json
    upvoted     =_extract(self._me.upvoted        , limit=None),
  File "/home/user/projects/rexport/src/rexport/export.py", line 67, in _extract
    return jsonify(list(from_(**kwargs)))
  File "/home/user/projects/rexport/src/rexport/export.py", line 42, in jsonify
    return [jsonify(x) for x in d]
  File "/home/user/projects/rexport/src/rexport/export.py", line 42, in <listcomp>
    return [jsonify(x) for x in d]
  File "/home/user/projects/rexport/src/rexport/export.py", line 56, in jsonify
    return jsonify(vars(d))
  File "/home/user/projects/rexport/src/rexport/export.py", line 45, in jsonify
    return {k: jsonify(v) for k, v in d.items() if k not in IGNORED_KEYS}
  File "/home/user/projects/rexport/src/rexport/export.py", line 45, in <dictcomp>
    return {k: jsonify(v) for k, v in d.items() if k not in IGNORED_KEYS}
  File "/home/user/projects/rexport/src/rexport/export.py", line 56, in jsonify
    return jsonify(vars(d))
  File "/home/user/projects/rexport/src/rexport/export.py", line 45, in jsonify
    return {k: jsonify(v) for k, v in d.items() if k not in IGNORED_KEYS}
  File "/home/user/projects/rexport/src/rexport/export.py", line 45, in <dictcomp>
    return {k: jsonify(v) for k, v in d.items() if k not in IGNORED_KEYS}
  File "/home/user/projects/rexport/src/rexport/export.py", line 42, in jsonify
    return [jsonify(x) for x in d]
  File "/home/user/projects/rexport/src/rexport/export.py", line 42, in <listcomp>
    return [jsonify(x) for x in d]
  File "/home/user/projects/rexport/src/rexport/export.py", line 61, in jsonify
    raise RuntimeError(f"Unexpected type: {type(d)}")
RuntimeError: Unexpected type: <class 'praw.models.reddit.poll.PollOption'>
```

**Comment by xdrie** [comment]
Never mind, I added `PollOption` too and it seems to work. I will confirm that it's working properly and send a PR.
